spring:
  application:
    name: MockProject_062026_Group3
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=NursingHomeManagement_V3;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect